Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder ".", "/vagrant"

  # ================= JENKINS MASTER =================
  config.vm.define "jenkins-master" do |master|
    master.vm.hostname = "jenkins-master"
    master.vm.network "private_network", ip: "192.168.56.10"

    # Доступ з хоста: http://localhost:8090
    master.vm.network "forwarded_port", guest: 8080, host: 8090, auto_correct: true

    master.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus  = 3
    end

    master.vm.provision "shell", path: "provision/master.sh"
  end

  # ================= JENKINS WORKER =================
  config.vm.define "jenkins-worker" do |worker|
    worker.vm.hostname = "jenkins-worker"
    worker.vm.network "private_network", ip: "192.168.56.11"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus  = 3
    end

    worker.vm.provision "shell", path: "provision/worker.sh"
  end
end
